[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'
remappings = [
    "@teleporter/=lib/teleporter/contracts/teleporter/",
    "@openzeppelin-upgradeable-v5/=lib/openzeppelin-v5/contracts/",
    "@openzeppelin-v5/=lib/openzeppelin-upgradeable-v5/contracts/"
]
[profile.dependencies]
teleporter = { git = "https://github.com/ava-labs/teleporter", tag = "v1.0.7" }
